### ISSUE TITLE
IHasComponent::getComponent is named "createComponent" in wiki

### ISSUE THREAD

**Issue by AlexeyGorovoy** [ValeryPonomarenko/ComponentsManager#2]
This page states that the function's name is `createComponent()`:

https://github.com/ValeryPonomarenko/ComponentsManager/wiki/Bind-to-the-Application

While in fact this method is currently named `getComponent()`:

https://github.com/ValeryPonomarenko/ComponentsManager/blob/0e7e5d273cff2b8b345dc91c5e0c8bed3c78bf65/injectionmanager/src/main/java/me/vponomarenko/injectionmanager/IHasComponent.kt#L13

 PS: I know it's easier to change wiki texts, but I really like `createComponent()` better 🙂

**Comment by ValeryPonomarenko** [comment]
Unfortunately, I can't do it :( so I'll fix wiki pages
