### ISSUE TITLE
How to unbind already bounded component and rebind another one

### ISSUE THREAD

**Issue by automaticqa** [ValeryPonomarenko/ComponentsManager#5]
I have some component.        

```
CompatInjectionManager.instance.bindComponent(object : IHasComponent<NetworkComponent> {
            override fun getComponent() = DaggerNetworkComponent.builder()
                    .apiModule(**apiModuleOffline**)     // here i have another variant
                    .iNetworkDependencies(CompatInjectionManager.instance.findComponent())
                    .build()
```

In some optional case i want to rebind that component with another parameter:
```
CompatInjectionManager.instance.bindComponent(object : IHasComponent<NetworkComponent> {
            override fun getComponent() = DaggerNetworkComponent.builder()
                    .apiModule(apiModuleONLINE**) // another parameter
                     ...
```

Could you please tell me how to do that  ?  
Thanks a lot!

**Comment by ValeryPonomarenko** [comment]
Hi! Thank you for your question.
I am sorry for the late reply.

I guess you can bind a component with custom lifecycle, so you can destroy the component whenever you want and bind another one.
Here is the wiki page - [Custom lifecycle](https://github.com/ValeryPonomarenko/ComponentsManager/wiki/Custom-lifecycle)
